### ISSUE TITLE
I may have mistakenly pushed my updates to the master.js

### ISSUE THREAD

**Issue by jvturner** [learn-co-curriculum/phase-1-monsters#2]
Good Evening,

I just wanted to notify the admin of this curriculum that I may have mistakenly updated the master.js file in this lab by mistake.  I was finishing up an assignment for school.  I did not notice the issue until I proceeded to |git add .| git commit -m "Completed Assignment"| and git push| in my Ubuntu terminal.  If so I apologize for this error.  I am usually pretty good with forking a copy to my personal github and not making this mistake.  
![Screenshot 2022-05-08 phase-1-monsters](https://user-images.githubusercontent.com/100874252/167337477-baae7aac-6138-4e9e-94f3-8facf32bbb4f.png)

I think everything may be okay.... but just wanted to reach out to be on the safe side.  I've attached a screenshot for reference.... Enjoy the evening.

-Jamond Turner

**Comment by lizbur10** [comment]
Hi @jvturner - thanks for letting us know! However, it looks like you did it just fine. If you look at the top left of the screenshot, you'll see that you are in your GitHub account, which means you correctly forked the lab! 

Also, even if you do accidentally push your changes to the canonical branch (which students do do from time to time), you don't have permissions on the learn-co-curriculum account to actually make the change. So no worries 😄 

Cheers! 💙
